MTable/bcre/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('accounts/', include('accounts.urls')),
    path('contacts/',include('contacts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

MTable/listings/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='listings'),
    path('<int:listing_id>', views.listing, name='listing'),
    path('search', views.search, name='search')
]

MTable/listings/models.py
from django.db import models
from realtors.models import Realtor
from datetime import datetime
from listings.choices import district_choices

# Create your models here.
class Listing(models.Model):
    realtor = models.ForeignKey(Realtor, on_delete=models.DO_NOTHING) 
    title = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    street = models.CharField(max_length=200)
    district = models.CharField(max_length=50,
    choices=district_choices.items())
    description = models.TextField(blank=True)
    price = models.IntegerField()
    bedrooms = models.CharField(max_length=200)
    bathrooms = models.CharField(max_length=200)
    clubhouse = models.CharField(max_length=200)
    sqft = models.IntegerField()
    estate_size =  models.CharField(max_length=200)
    is_published = models.BooleanField(default=True)
    list_date = models.DateTimeField(default=datetime.now, blank=True)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)

    def __str__(self):
        return f"House Title : {self.title}"

MTable/listings/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Listing
from listings.choices import price_choices,bedroom_choices,district_choices
# Create your views here.
def index(request):
    listings = Listing.objects.order_by('-list_date').filter(is_published=True)
    paginator = Paginator(listings,3)
    page = request.GET.get("page")
    paged_listings = paginator.get_page(page)
    context = {
        'listings':paged_listings
        }
    return render(request,'listings/listings.html',context)

def listing(request,listing_id):
    listing = get_object_or_404(Listing,pk=listing_id)
    context = {
        'listing':listing,
    }
    return render(request,'listings/listing.html',context)

def search(request):
    queryset_listings = Listing.objects.order_by('-list_date')
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
    if keywords:
        queryset_listings = queryset_listings.filter(description__icontains = keywords)
    if 'title' in request.GET:
        title = request.GET['title']
    if title:
        queryset_listings = queryset_listings.filter(title__icontains = title)
    if 'district' in request.GET:
        district = request.GET['district']
        if district:
            if district != '_':
                queryset_listings = queryset_listings.filter(district__iexact = district)
    if 'price' in request.GET:
        price = request.GET['price']
        if price:
            queryset_listings = queryset_listings.filter(price__lte = price)
    if 'bedrooms' in request.GET:
        bedrooms = request.GET['bedrooms']
        if bedrooms:
            queryset_listings = queryset_listings.filter(bedrooms__lte = bedrooms)
    context = {
            'price_choices':price_choices,
            'bedroom_choices':bedroom_choices,
            'district_choices':district_choices,
            'listings' : queryset_listings,
            'values' : request.GET
        }
    return render(request,'listings/search.html',context)

MTable/templates/listings/listing.html
{% extends 'base.html' %}
{% load static %} {% load humanize %}
{% block title %} | {{ listing.title |title }} {% endblock title %}
{% block content %}
    <!-- Showcase -->
     {% include "partials/_alert.html" %}
  
      <!-- Breadcrumb -->
      <section id="bc" class="mt-3">
        <div class="container">
          <nav>
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="{% url 'index' %}">Home</a>
              </li>
              <li class="breadcrumb-item">
                <a href="{% url 'listings' %}">Branch</a>
              </li>
              <li class="breadcrumb-item active">{{ listing.title }}</li>
            </ol>
          </nav>
        </div>
      </section>
  
      <!-- Listing -->
      <section id="listing" class="py-4">
        <div class="container">
          <a href="{% url 'listings' %}" class="btn btn-light mb-4">Back To Lists</a>
          <div class="row">
            <div class="col-md-9">
              <!-- Home Main Image -->
              <img
                src={{ listing.photo_main.url }}
                alt=""
                class="img-main img-fluid mb-3"
              />
              <!-- Thumbnails -->
              <div class="row mb-5 thumbs">
                {% if listing.photo_1 %}
                <div class="col-md-2">
                  <a
                    href={{ listing.photo_1.url }}
                    data-lightbox="home-images"
                  >
                    <img
                      src={{ listing.photo_1.url }}
                      alt=""
                      class="img-fluid"
                    />
                  </a>
                </div>
                {% endif %}
                {% if listing.photo_2 %}
                <div class="col-md-2">
                  <a
                    href={{ listing.photo_2.url }}
                    data-lightbox="home-images"
                  >
                    <img
                      src={{ listing.photo_2.url }}
                      alt=""
                      class="img-fluid"
                    />
                  </a>
                </div>
                {% endif %}
                {% if listing.photo_3 %}
                <div class="col-md-2">
                  <a
                    href={{ listing.photo_3.url }}
                    data-lightbox="home-images"
                  >
                    <img
                      src={{ listing.photo_3.url }}
                      alt=""
                      class="img-fluid"
                    />
                  </a>
                </div>
                {% endif %}
                {% if listing.photo_4 %}
                <div class="col-md-2">
                  <a
                    href={{ listing.photo_4.url }}
                    data-lightbox="home-images"
                  >
                    <img
                      src={{ listing.photo_4.url }}
                      alt=""
                      class="img-fluid"
                    />
                  </a>
                </div>
                {% endif %}
                {% if listing.photo_5 %}
                <div class="col-md-2">
                  <a
                    href={{ listing.photo_5.url }}
                    data-lightbox="home-images"
                  >
                    <img
                      src={{ listing.photo_5.url }}
                      alt=""
                      class="img-fluid"
                    />
                  </a>
                </div>
                {% endif %}
                {% if listing.photo_6 %}
                <div class="col-md-2">
                  <a
                    href={{ listing.photo_6.url }}
                    data-lightbox="home-images"
                  >
                    <img
                      src={{ listing.photo_6.url }}
                      alt=""
                      class="img-fluid"
                    />
                  </a>
                </div>
                {% endif %}
              </div>
              <!-- Fields -->
              <div class="row mb-5 fields">
                <div class="col-md-6">
                  <ul class="list-group list-group-flush">
                    <!-- Modified Date: 2025-01-18 -->
                    <!-- Modified Content: Changed key and value text color to white, background to black and gold -->
                    <li class="list-group-item bg-dark text-white border-warning">
                      <div class="d-flex justify-content-between align-items-center">
                        <div>
                          <i class="fas fa-money-bill-alt text-white"></i> Price <!-- White icon -->
                        </div>
                        <div class="text-white">
                          {{ listing.price|intcomma }} <!-- White value -->
                        </div>
                      </div>
                    </li>
                    <li class="list-group-item bg-dark text-white border-warning">
                      <div class="d-flex justify-content-between align-items-center">
                        <div>
                          <i class="fa-solid fa-music text-white"></i> Band <!-- White icon -->
                        </div>
                        <div class="text-white">
                          {{ listing.bedrooms }} <!-- White value -->
                        </div>
                      </div>
                    </li>
                    <li class="list-group-item bg-dark text-white border-warning">
                      <div class="d-flex justify-content-between align-items-center">
                        <div>
                          <i class="fa-solid fa-user text-white"></i> Guest <!-- White icon -->
                        </div>
                        <div class="text-white">
                          {{ listing.bathrooms }} <!-- White value -->
                        </div>
                      </div>
                    </li>
                    <li class="list-group-item bg-dark text-white border-warning">
                      <div class="d-flex justify-content-between align-items-center">
                        <div>
                          <i class="fa-solid fa-chair text-white"></i> Seat <!-- White icon -->
                        </div>
                        <div class="text-white">
                          {{ listing.clubhouse }} <!-- White value -->
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
                <div class="col-md-6">
                  <ul class="list-group list-group-flush">
                    <!-- Modified Date: 2025-01-18 -->
                    <!-- Modified Content: Changed key and value text color to white, background to black and gold -->
                    <li class="list-group-item bg-dark text-white border-warning">
                      <div class="d-flex justify-content-between align-items-center">
                        <div>
                          <i class="fas fa-th-large text-white"></i> Exquisite Dimensions <!-- White icon -->
                        </div>
                        <div class="text-white">
                          {{ listing.sqft }} <!-- White value -->
                        </div>
                      </div>
                    </li>
                    <li class="list-group-item bg-dark text-white border-warning">
                      <div class="d-flex justify-content-between align-items-center">
                        <div>
                          <i class="fa-solid fa-utensils text-white"></i> Course <!-- White icon -->
                        </div>
                        <div class="text-white">
                          {{ listing.estate_size }} <!-- White value -->
                        </div>
                      </div>
                    </li>
                    <li class="list-group-item bg-dark text-white border-warning">
                      <div class="d-flex justify-content-between align-items-center">
                        <div>
                          <i class="fas fa-calendar text-white"></i> Offered From <!-- White icon -->
                        </div>
                        <div class="text-white">
                          {{ listing.list_date|timesince }} <!-- White value -->
                        </div>
                      </div>
                    </li>
                    <li class="list-group-item bg-dark text-white border-warning">
                      <div class="d-flex justify-content-between align-items-center">
                        <div>
                          <i class="fa-solid fa-chess-pawn text-white"></i> Head Chef <!-- White icon -->
                        </div>
                        <div class="text-white">
                          {{ listing.realtor }} <!-- White value -->
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
  
              <!-- Description -->
              <div class="row mb-5">
                <div class="col-md-12">
                  {{ listing.description }}
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <div class="card mb-3">
                <img
                  class="card-img-top"
                  src={{ listing.realtor.photo.url }}
                  alt="Seller of the month"
                />
                <div class="card-body">
                  <h5 class="card-title">Head Chef</h5>
                  <h6 class="text-warning">{{ listing.realtor }}</h6>
                </div>
              </div>
              <!-- Modified More Info Button -->
              <button
                class="btn-primary btn-block btn-lg"
                data-toggle="modal"
                data-target="#inquiryModal"
                style="background-color: #1a1a1a; color: white; border: 2px solid #d4af37; border-radius: 0; font-weight: bold; text-transform: uppercase; transition: background-color 0.3s ease, color 0.3s ease;"
                onmouseover="this.style.backgroundColor='#d4af37'; this.style.color='#1a1a1a'; this.style.borderColor='#1a1a1a';"
                onmouseout="this.style.backgroundColor='#1a1a1a'; this.style.color='white'; this.style.borderColor='#d4af37';"
              >
                Make A Reservation
              </button>
            </div>
          </div>
        </div>
      </section>
  
<!-- Inquiry Modal -->
<div class="modal fade" id="inquiryModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="inquiryModalLabel">Make A Reservation</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'contact' %}" method='POST'>
          {% csrf_token %}
          <!-- Check user and get ID -->
          {% if user.is_authenticated %}
          <input type="hidden" name="user_id" value="{{ user.id }}" />
          {% else %}
          <input type="hidden" name="user_id" value=0 />
          {% endif %}
          <input type="hidden" name="realtor_email" value="{{ listing.realtor.email }}"/>
          <input type="hidden" name="listing_id" value="{{ listing.id }}" />
          <div class="form-group">
            <label for="property_name" class="col-form-label">Location:</label>
            <input
              type="text"
              name="listing_title"
              class="form-control"
              value="{{ listing.title }}"
            />
          </div>
          <div class="form-group">
            <label for="name" class="col-form-label">Name:</label>
            <input
              type="text"
              name="name"
              class="form-control"
              {% if user.is_authenticated %}
              value="{{ user.first_name }} {{ user.last_name}}"
              {% endif %}
              required
            />
          </div>
          <div class="form-group">
            <label for="email" class="col-form-label">Email:</label>
            <input
              type="email"
              name="email"
              class="form-control"
              {% if user.is_authenticated %}
              value="{{ user.email }}"
              {% endif %}
              required
            />
          </div>
          <div class="form-group">
            <label for="phone" class="col-form-label">Phone:</label>
            <input
              type="text"
              name="phone"
              class="form-control"
            />
          </div>
          <div class="form-group">
            <label for="message" class="col-form-label">Message:</label>
            <textarea
              name="message"
              class="form-control"
            ></textarea>
          </div>
          <hr />
          <!-- Modified Date: 2025-01-18 -->
          <!-- Modified Content: Increased Send button size to double and changed to black and gold style -->
          <input
            type="submit"
            value="Send"
            class="btn btn-block btn-lg"
            style="
              background-color: #1a1a1a; /* Black background */
              color: #d4af37; /* Gold text */
              border: 2px solid #d4af37; /* Gold border */
              font-size: 1.5rem; /* Double size */
              font-weight: bold; /* Bold text */
              padding: 10px 20px; /* Increased padding */
            "
          />
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

MTable/templates/listings/listings.html
{% extends 'base.html' %} 
{% load humanize %} 
{% block content %}
  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href={% url "index" %}> <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active">Browse Branches</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listings -->
  <section id="listings" class="py-4">
    <div class="container">
      <div class="row">
        <!-- Listing 1 -->
         {% if listings %}
         {% for listing in listings %}
        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card listing-preview">
            <img class="card-img-top" src={{ listing.photo_main.url }} alt="" />
            <div class="card-img-overlay">
              <h2>
                <!-- Modified price tag to black and gold style -->
                <span class="badge badge-dark text-warning">${{listing.price | intcomma}}</span>
              </h2>
            </div>
            <div class="card-body">
              <div class="listing-heading text-center">
                <h4 class="text-primary">{{listing.title|title}}</h4>
                <p>
                  <i class="fas fa-map-marker text-secondary"></i>{{ listing.get_district_display }} 
                </p>
              </div>
              <hr />
              <div class="row py-2">
                <div class="col-12">
                  <div class="bg-dark text-white border-warning p-2"> <!-- Black and gold background + white text -->
                    <div class="row">
                      <div class="col-6">
                        <i class="fas fa-th-large text-warning"></i> Scale: {{listing.sqft | intcomma}} <!-- Gold icon -->
                      </div>
                      <div class="col-6">
                        <i class="fa-solid fa-chair text-warning"></i> Seat: {{listing.clubhouse}} <!-- Gold icon -->
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row py-2">
                <div class="col-12">
                  <div class="bg-dark text-white border-warning p-2"> <!-- Black and gold background + white text -->
                    <div class="row">
                      <div class="col-6">
                        <i class="fa-solid fa-music text-warning"></i> Band: {{listing.bedrooms}} <!-- Gold icon -->
                      </div>
                      <div class="col-6">
                        <i class="fa-solid fa-user text-warning"></i> Guest: {{listing.bathrooms}} <!-- Gold icon -->
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <hr class="border-warning" /> <!-- Gold divider line -->
              <div class="row py-2">
                <div class="col-12">
                  <div class="bg-dark text-white border-warning p-2"> <!-- Black and gold background + white text -->
                    <i class="fa-solid fa-chess-pawn text-warning"></i> {{listing.realtor}} <!-- Gold icon -->
                  </div>
                </div>
              </div>
              <div class="row pb-2">
                <div class="col-12">
                  <div class="bg-dark text-white border-warning p-2"> <!-- Black and gold background + white text -->
                    <i class="fas fa-clock text-warning"></i> {{listing.list_date | timesince}} <!-- Gold icon -->
                  </div>
                </div>
              </div>
              <hr />
              <!-- Modified More Info button to black and gold style -->
              <a href={% url "listing" listing.id %} class="btn btn-dark btn-block text-warning"
                >More Info</a
              >
            </div>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col-md-12">
          <p>No Listing Available</p>
        </div>
        {% endif %}
      </div>

      <!-- Pagination -->
      <div class="row">
        <div class="col-md-12">
          {% if listings.has_other_pages %}
          <ul class="pagination">
            {% if listings.has_previous %}
            <!-- Previous page button: black and gold style -->
            <li class="page-item">
              <a class="page-link bg-dark text-warning border-dark" href="?page={{listings.previous_page_number}}">&laquo;</a>
            </li>
            {% else %}
            <!-- Previous page button (disabled): black and gold style -->
            <li class="page-item disabled">
              <a class="page-link bg-dark text-warning border-dark" href="#">&laquo;</a>
            </li>
            {% endif %}
            {% for i in listings.paginator.page_range %}
            {% if listings.number == i %}
            <!-- Current page button: black and gold style -->
            <li class="page-item active">
              <a class="page-link bg-dark text-warning border-dark">{{i}}</a>
            </li>
            {% else %}
            <!-- Other page buttons: black and gold style -->
            <li class="page-item">
              <a class="page-link bg-dark text-warning border-dark" href="?page={{i}}">{{i}}</a>
            </li>
            {% endif %}
            {% endfor %}
            {% if listings.has_next %}
            <!-- Next page button: black and gold style -->
            <li class="page-item">
              <a class="page-link bg-dark text-warning border-dark" href="?page={{listings.next_page_number}}">&raquo;</a>
            </li>
            {% else %}
            <!-- Next page button (disabled): black and gold style -->
            <li class="page-item disabled">
              <a class="page-link bg-dark text-warning border-dark" href="#">&raquo;</a>
            </li>
            {% endif %}
          </ul>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

MTable/templates/listings/search.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<!-- Add custom styles -->
<style>
  /* Black and gold style button */
  .btn-black-gold {
    background-color: black; /* Black background */
    color: gold; /* Gold text */
    border: 1px solid gold; /* Gold border */
  }

  /* Black and gold style price badge */
  .badge-black-gold {
    background-color: black; /* Black background */
    color: gold; /* Gold text */
    border: 1px solid gold; /* Gold border */
  }
</style>

<section id="showcase-inner" class="showcase-search text-white py-5">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <form action="{% url 'search' %}">
          <!-- Form Row 1: Location and Price -->
          <div class="form-row">
            <!-- Location Search -->
            <div class="col-md-6 mb-3">
              <label class="sr-only">Location</label>
              <select name="district" class="form-control">
                <option selected="true" disabled="disabled">
                  Location (Select)
                </option>
                {% for key, value in district_choices.items %}
                <option value="{{ key }}" {% if key == values.district %}selected{% endif %}>
                  {{ value }}
                </option>
                {% endfor %}
              </select>
            </div>

            <!-- Price Search -->
            <div class="col-md-6 mb-3">
              <select name="price" class="form-control">
                <option selected="true" disabled="disabled">
                  Cost (Select)
                </option>
                {% for key, value in price_choices.items %}
                <option value="{{ key }}" {% if key == values.price %}selected{% endif %}>
                  {{ value }}
                </option>
                {% endfor %}
              </select>
            </div>
          </div>

          <!-- Form Row 2: Keyword -->
          <div class="form-row">
            <div class="col-md-12 mb-3">
              <label class="sr-only">Keywords</label>
              <input
                type="text"
                name="keywords"
                class="form-control"
                placeholder="Keyword (Band, Guest, etc)"
                value="{{ values.keywords }}"/>  <!-- Retain user input for keywords -->
              
            </div>
          </div>

          <!-- Hidden Fields for Title and Tables (Default to Empty) -->
          <input type="hidden" name="title" value="">
          <input type="hidden" name="bedrooms" value="">

          <!-- Modified Submit button to black and gold style -->
          <button class="btn btn-black-gold btn-block mt-4" type="submit">
            Submit form
          </button>
        </form>
      </div>
    </div>
  </div>
</section>

  <!-- Listings -->
  <section id="listings" class="py-4">
    <div class="container">
      <div class="row">
        {% if listings %}
        {% for listing in listings %}
        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card listing-preview">
            <img
              class="card-img-top"
              src="{{ listing.photo_main.url }}"
              alt=""
            />
            <div class="card-img-overlay">
              <h2>
                <!-- Modified price badge to black and gold style -->
                <span class="badge badge-black-gold">${{ listing.price|intcomma }}</span>
              </h2>
            </div>
            <div class="card-body">
              <div class="listing-heading text-center">
                <h4 class="text-primary">{{listing.title | title}}</h4>
                <p>
                  <i class="fas fa-map-marker text-secondary"></i>{{listing.get_district_display}}
                </p>
              </div>
              <hr />
              <div class="row py-2">
                <div class="col-6">
                  <i class="fas fa-th-large" style="color: #001F3F;"></i> 
                  <span style="color: #001F3F;">Scale:</span> 
                  <span style="color: #001F3F;">{{ listing.sqft|intcomma }}</span>
                </div>
                <div class="col-6">
                  <i class="fa-solid fa-chair" style="color: #001F3F;"></i> 
                  <span style="color: #001F3F;">Seat:</span> 
                  <span style="color: #001F3F;">{{ listing.clubhouse }}</span>
                </div>
              </div>
              <div class="row py-2">
                <div class="col-6">
                  <i class="fa-solid fa-music" style="color: #001F3F;"></i> 
                  <span style="color: #001F3F;">Band:</span> 
                  <span style="color: #001F3F;">{{ listing.bedrooms }}</span>
                </div>
                <div class="col-6">
                  <i class="fa-solid fa-user" style="color: #001F3F;"></i> 
                  <span style="color: #001F3F;">Guest:</span> 
                  <span style="color: #001F3F;">{{ listing.bathrooms }}</span>
                </div>
              </div>
              <hr />
              <div class="row py-2">
                <div class="col-12">
                  <i class="fa-solid fa-chess-pawn" style="color: #001F3F;"></i> 
                  <span style="color: #001F3F;">{{ listing.realtor.name }}</span>
                </div>
              </div>
              <div class="row pb-2">
                <div class="col-6">
                  <i class="fas fa-clock" style="color: #001F3F;"></i> 
                  <span style="color: #001F3F;">{{ listing.list_date|timesince }}</span>
                </div>
              </div>
              <hr />
              <!-- Modified More Info button to black and gold style -->
              <a href="{% url 'listing' listing.id %}" class="btn btn-black-gold btn-block"
                >More Info</a
              >
            </div>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col-md-12">
        <p>No Branches found</p>
        </div>
        {% endif%}

      </div>
    </div>
  </section>

{% endblock %}